name: Build e Deploy EC2

on:
  push:
    branches: [ "main" ]

env:
  GITHUB_USER: ${{ secrets.Login }}
  GITHUB_PASSWORD: ${{ secrets.Senha }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . backend
      
  deploy:
    runs-on: self-hosted
    needs: build
    
    steps:
    - uses: actions/checkout@v3
    - name: Mudar Caminho
      run: cd ./cefetpark-backend/CefetPark_Backend

    - uses: actions/checkout@v3
    - name: Pull in Repository
      run: git pull origin main

    - uses: actions/checkout@v3
    - name: Login in Repository
      run: ${{ secrets.Login }}

    - uses: actions/checkout@v3
    - name: Password in Repository
      run: ${{ secrets.Senha }}
      

    steps:
    - uses: actions/checkout@v3
    - name: Stop current container
      continue-on-error: true
      run: docker stop backend
      
    - uses: actions/checkout@v3
    - name: Rm current container
      continue-on-error: true
      run: docker rm backend
    
    - uses: actions/checkout@v3
    - name: Rm current imagem
      run: docker rmi cefetpark-backend
    
    - uses: actions/checkout@v3
    - name: Build imagem
      run: docker build -t cefetpark-backend .
    
    - uses: actions/checkout@v3
    - name: Run image
      run: docker run -d --name backend -p 8080:80 cefetpark-backend