version: '3'
services:
  dotnet-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: my-dotnet-app
    ports:
      - "8080:80"
      - "443:443"  # Mapeia a porta 443 para o HTTPS
    depends_on:
      - redis
    networks:
      - my-network
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=teste
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    networks:
      - my-network

networks:
  my-network: