version: '3'
services:
  dotnet-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: my-dotnet-app
    ports:
      - "8080:80"
    depends_on:
      - redis
    networks:
      - my-network

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    networks:
      - my-network

networks:
  my-network: