name: Build e Deploy EC2

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore --environment "Production"
      - name: Test
        run: dotnet test --no-restore --verbosity normal
 
  deploy:
    needs: build
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    - name: Reset Terminal
      run: cd
    
    - uses: actions/checkout@v3
    - name: Go to Repository
      run: cd /home/ubuntu/cefetpark-backend/CefetPark_Backend

    - uses: actions/checkout@v3
    - name: Pull in Repository
      run: git pull origin main
      
    - uses: actions/checkout@v3
    - name: Docker compose down
      continue-on-error: true
      run: sudo docker-compose down
      
    - uses: actions/checkout@v3
    - name: Docker system prune
      run: sudo docker system prune --all --force --volumes
    
    - uses: actions/checkout@v3
    - name: Docker compose up
      run: sudo docker-compose up --build -d
