name: Build e Deploy EC2

on:
  push:
    branches: [ "main" ]

env:
  GITHUB_USER: ${{ secrets.Login }}
  GITHUB_PASSWORD: ${{ secrets.Senha }}

jobs:
 
  deploy:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    - name: Reset Terminal
      run: cd
    
    - uses: actions/checkout@v3
    - name: Go to Repository
      run: cd /home/ubuntu/cefetpark-backend/CefetPark_Backend

    - uses: actions/checkout@v3
    - name: Pull in Repository
      run: git pull origin main
      
    - uses: actions/checkout@v3
    - name: Docker compose down
      continue-on-error: true
      run: sudo docker-compose down
      
    - uses: actions/checkout@v3
    - name: Docker system prune
      run: sudo docker system prune --all --force --volumes
    
    - uses: actions/checkout@v3
    - name: Docker compose up
      run: sudo docker-compose up
