name: Build e Deploy EC2

on:
  push:
    branches: [ "main" ]

env:
  GITHUB_USER: ${{ secrets.Login }}
  GITHUB_PASSWORD: ${{ secrets.Senha }}

jobs:
 
  deploy:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    - name: Reset Terminal
      run: cd
    
    - uses: actions/checkout@v3
    - name: Go to Repository
      run: cd /home/ubuntu/cefetpark-backend/CefetPark_Backend/src

    - uses: actions/checkout@v3
    - name: Pull in Repository
      run: git pull origin main

    - uses: actions/checkout@v3
    - name: Login in Repository
      run: ${{ secrets.Login }}

    - uses: actions/checkout@v3
    - name: Password in Repository
      run: ${{ secrets.Senha }}
      
    - uses: actions/checkout@v3
    - name: Stop current container
      continue-on-error: true
      run: sudo docker stop backend
      
    - uses: actions/checkout@v3
    - name: Rm current container
      continue-on-error: true
      run: sudo docker rm backend
    
    - uses: actions/checkout@v3
    - name: Rm current imagem
      run: sudo docker rmi cefetpark-backend
    
    - uses: actions/checkout@v3
    - name: Build imagem
      run: sudo docker build -t cefetpark-backend .
    
    - uses: actions/checkout@v3
    - name: Run image
      run: sudo docker run -d --name backend -p 8080:80 cefetpark-backend
